
apiVersion: v1
kind: Pod
metadata:
  name: secret-devops
  labels:
    name: myapp
spec:
  volumes:
    - name: secret-volume-devops
      secret:
        secretName: beta
  containers:
    - name: secret-container-devops
      image: ubuntu:latest
      command: ["/bin/bash", "-c", "sleep 10000"]
      volumeMounts:
        - name: secret-volume-devops
          mountPath: /opt/apps
          readOnly: true
